### ISSUE TITLE
Jinja2 - XSS and other vulnerabilities

### ISSUE THREAD

**Issue by tsingh2k15** [Snowflake-Labs/schemachange#92]
By default, Jinja 2 will not sanitize or escape input to templates. This leaves rendered templates open to XSS and other vulnerabilities. 

Jinja offers the ability to sanitize with the `autoescape `argument on the Environment or Template initializer, however this is `False `by default. It could be better to set it `True` for safety.  

As of Jinja 2.4 `autoescape `can also be a callable that is passed the template name and could return `True `or `False`. I believe `autoescape` can be set to `True` unconditionally for this cli tool. Thoughts?

Proposing a fix in https://github.com/Snowflake-Labs/schemachange/pull/93

**Comment by sfc-gh-jhansen** [comment]
Merged and deployed, thanks!

**Comment by tsingh2k15** [comment]
> Merged and deployed, thanks!

I will include the necessary updates(change-logs, version increments...) in my future PRs. Thanks for incorporating with https://github.com/Snowflake-Labs/schemachange/commit/884c2c0b2d007d05e69141c076b132590a122b85

**Comment by akdor1154** [comment]
I don't think this is quite the right approach - jinja autoescaping is designed for where the output language is HTML. Here the output language will be SQL, so you don't want to go messing with HTML entities, quote semantics will be different, etc, right?

**Comment by sfc-gh-jhansen** [comment]
What do you suggest instead @akdor1154?

**Comment by akdor1154** [comment]
Honestly I wouldn't try to go down this path at all - escaping is to protect your templates against untrusted input, and I would hope nobody is passing untrusted input to their db migration scripts :)

For the security aspect, doco  that vars are subbed in directly by string replacement should be sufficient I guess?

Just checking and it doesn't look like DBT, Flyway, even SnowSQL don't go down this path at all (it was a very brief check though..). In theory you *could* implement an escaping system targeted at SQL, but this would be a pretty big project in itself - because of how SQL works, it would need to be aware of if you're trying to sub in column identifiers, literals, bits of sql code, etc..

**Comment by akdor1154** [comment]
@tsingh2k15  in case i'm missing something, what scenario did you have in mind to protect against?

**Comment by sfc-gh-jhansen** [comment]
Yeah, I didn't do a careful review here before publishing, but I agree with you @akdor1154. Other than not really being helpful (since we're not dealing with HTML/XML), it will also cause problems with strings which legitimately need to include a <, >, or & (like a password).

Unless there's something I'm missing I'm planning to roll back this change @tsingh2k15.

**Comment by saperry** [comment]
Enabling autoescape does cause issues. With 3.3.2 using `schemachange render R__test.sql`

test.sql
```
SELECT * FROM TABLE WHERE COL {{">"}} 45;
SELECT * FROM TABLE WHERE COL > 45;
```
becomes

```
SELECT * FROM TABLE WHERE COL &gt; 45;
SELECT * FROM TABLE WHERE COL > 45
```

[The jinja documentation](https://jinja.palletsprojects.com/en/3.0.x/api/#autoescaping) suggests setting a default so would be good to set autoescape=False.

**Comment by sfc-gh-jhansen** [comment]
Just published 3.3.3 with a change from #95, and set the default for autoescape to False.

**Comment by tsingh2k15** [comment]
@saperry @sfc-gh-jhansen 

 I am okay with reverting back to defaults. Thanks for pointing this out. Sharing my thoughts below.

**1)** I did not fully consider the scenarios mentioned above earlier that could break with this change, but your concerns are valid. My main thought around this was to prevent the vulnerabilities in general as someone could intentionally inject HTML/XML files in the SQL scripts directory? and then let the tool load it that way trying to simulate XSS?  Seems like the tool allows loading and rendering of HTML/XML templates? I was just trying it to check the behavior via below snippet.

```
def test_xss():
    processor = JinjaTemplateProcessor("", None)
    templates = {"test.html": "<html><body> Hello {{person}}</body></html>"}
    processor.override_loader(DictLoader(templates))
    test_vars = json.loads('{"person": "<script type=\'javascript\'>alert(\'I am an XSS flaw!\')</script>"}')
    context = processor.render("test.html", test_vars, True)
```

**2)** On another thought, if the tool does not prevent loading XML/HTML templates, could it check for a template type and then use a callable(per below doc) to return True or False accordingly? Just a thought. Not sure if this is really worth exploring. Could be explored if security is still a concern per scenario I mentioned.

`As of Jinja 2.4 autoescape  can also be a callable that is passed the template name and has to return True or False`

**Comment by holtalanm** [comment]
@tsingh2k15  correct me if I'm wrong, but wouldn't that require this tool to be executing untrusted inputs?  I'll mirror what someone else said earlier about this:  I would hope no one is passing untrusted inputs to their database migrations.

Regardless, even with auto-escaping, variables that you don't want to get auto-escaped can be marked safe with `|safe` within the jinja template, so I'm not certain it makes much of a difference either way, as long as this behavior _is documented_.  

I'm currently using v3.3.2 and got burned by this undocumented change, simply because I had no clue that schemachange was using non-default settings for jinja.
